export const MOCK_JOBS = [
  // 원티드
  { id: 'w1', site: 'wanted', title: '마케팅 매니저', company: '카카오', location: '판교', type: '정규직' },
  { id: 'w2', site: 'wanted', title: '콘텐츠 마케터', company: '네이버', location: '분당', type: '정규직' },
  { id: 'w3', site: 'wanted', title: '퍼포먼스 마케터', company: '쿠팡', location: '서울', type: '정규직' },
  { id: 'w4', site: 'wanted', title: 'SNS 마케팅 담당자', company: '라인', location: '신촌', type: '계약직' },
  { id: 'w5', site: 'wanted', title: '브랜드 마케터', company: '무신사', location: '서울', type: '정규직' },
  { id: 'w6', site: 'wanted', title: '서비스 기획자', company: '토스', location: '서울', type: '정규직' },
  { id: 'w7', site: 'wanted', title: '프로덕트 매니저 (PM)', company: '배달의민족', location: '서울', type: '정규직' },
  { id: 'w8', site: 'wanted', title: '영업 담당자', company: '삼성전자', location: '수원', type: '정규직' },
  { id: 'w9', site: 'wanted', title: '인사 담당자 (HR)', company: '현대자동차', location: '양재', type: '정규직' },
  { id: 'w10', site: 'wanted', title: '백엔드 개발자', company: '라인', location: '신촌', type: '정규직' },
  { id: 'w11', site: 'wanted', title: '프론트엔드 개발자', company: '카카오', location: '판교', type: '정규직' },
  { id: 'w12', site: 'wanted', title: 'UX 디자이너', company: '쏘카', location: '서울', type: '정규직' },
  // 사람인
  { id: 's1', site: 'saramin', title: '마케팅 기획 신입', company: 'CJ제일제당', location: '서울', type: '정규직' },
  { id: 's2', site: 'saramin', title: 'MD 상품기획자', company: 'GS리테일', location: '서울', type: '정규직' },
  { id: 's3', site: 'saramin', title: '영업 관리 대리', company: 'LG전자', location: '여의도', type: '정규직' },
  { id: 's4', site: 'saramin', title: '회계/재무 담당자', company: 'KB금융그룹', location: '서울', type: '정규직' },
  { id: 's5', site: 'saramin', title: '홍보/PR 담당', company: '롯데쇼핑', location: '서울', type: '계약직' },
  { id: 's6', site: 'saramin', title: '고객센터 상담원', company: '신세계', location: '서울', type: '계약직' },
  { id: 's7', site: 'saramin', title: '그래픽 디자이너', company: '넥슨', location: '판교', type: '정규직' },
  { id: 's8', site: 'saramin', title: '마케팅 인턴', company: '올리브영', location: '서울', type: '인턴' },
  { id: 's9', site: 'saramin', title: '경영기획 담당자', company: '신한카드', location: '서울', type: '정규직' },
  { id: 's10', site: 'saramin', title: '콘텐츠 기획자', company: '카카오엔터', location: '판교', type: '정규직' },
  // 잡코리아
  { id: 'j1', site: 'jobkorea', title: '서비스 기획 PM', company: '카카오뱅크', location: '판교', type: '정규직' },
  { id: 'j2', site: 'jobkorea', title: '서비스 기획자 신입', company: '당근마켓', location: '서울', type: '정규직' },
  { id: 'j3', site: 'jobkorea', title: '영업/제휴 매니저', company: '야놀자', location: '서울', type: '정규직' },
  { id: 'j4', site: 'jobkorea', title: '인사 노무 담당자', company: 'SK하이닉스', location: '이천', type: '정규직' },
  { id: 'j5', site: 'jobkorea', title: '콘텐츠 크리에이터', company: '하이브', location: '용산', type: '정규직' },
  { id: 'j6', site: 'jobkorea', title: '구매/조달 담당자', company: '포스코', location: '포항', type: '정규직' },
  { id: 'j7', site: 'jobkorea', title: '개발자 (풀스택)', company: '토스', location: '서울', type: '정규직' },
  { id: 'j8', site: 'jobkorea', title: '마케팅/홍보 담당', company: '컬리', location: '서울', type: '정규직' },
  // 인크루트
  { id: 'i1', site: 'incruit', title: '마케팅 팀장급', company: '이마트', location: '서울', type: '정규직' },
  { id: 'i2', site: 'incruit', title: 'B2B 영업 담당', company: '두산', location: '중구', type: '정규직' },
  { id: 'i3', site: 'incruit', title: '재무/회계 신입', company: '한화', location: '서울', type: '정규직' },
  { id: 'i4', site: 'incruit', title: '인사/총무 담당', company: '현대건설', location: '서울', type: '정규직' },
  { id: 'i5', site: 'incruit', title: '전략기획 담당자', company: 'SK텔레콤', location: '을지로', type: '정규직' },
  { id: 'i6', site: 'incruit', title: '고객센터 팀장', company: 'KT', location: '광화문', type: '정규직' },
  { id: 'i7', site: 'incruit', title: '마케팅 기획 대리', company: '아모레퍼시픽', location: '용산', type: '정규직' },
];
